---
# tasks file for java

- name: set distro-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"
  ignore_errors: true

- include: "{{ ansible_os_family | lower }}_setup.yml"

- name: Copy policy files
  copy:
    src: "{{ item }}"
    dest: "{{ java_security_path }}/{{ item }}"
  with_items:
    - "{{ java_policy_files }}"
  tags:
    - setup
    - java

- name: Link systems cacerts file
  file:
    src: "{{ java_system_cacerts }}"
    dest: "{{ java_security_path }}/cacerts"
    state: link
    force: true
  tags:
    - setup
    - java
